export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const ADD_TO_CART= "ADD_TO_CART";
export const REMOVE_ITEM_FROM_CART= "REMOVE_ITEM_FROM_CART";
export const ADD_ITEM_QTY= "ADD_ITEM_QTY";
export  const REMOVE_ITEM_QTY= "REMOVE_ITEM_QTY";
